# Generated by Django 5.1.4 on 2024-12-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('str2words', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='user_id',
            new_name='user',
        ),
    ]
