# Generated by Django 5.1.4 on 2025-01-19 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickerData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hp', models.IntegerField()),
                ('iq', models.IntegerField()),
                ('happiness', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
